"""菜单增加path字段，存放菜单地址

Revision ID: 1e0cc7e9c46e
Revises: a601bfea69c7
Create Date: 2025-10-16 11:04:57.057940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0cc7e9c46e'
down_revision: Union[str, None] = 'a601bfea69c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('path', sa.String(length=256), nullable=True, comment='菜单地址'))
    op.create_index(op.f('ix_menus_path'), 'menus', ['path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menus_path'), table_name='menus')
    op.drop_column('menus', 'path')
    # ### end Alembic commands ###
