"""function add uri

Revision ID: 230963af0176
Revises: 35d1bff6a191
Create Date: 2025-08-05 15:16:05.843151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230963af0176'
down_revision: Union[str, None] = '35d1bff6a191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('uri', sa.String(length=256), nullable=True, comment='功能接口'))
    op.create_index(op.f('ix_functions_uri'), 'functions', ['uri'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_functions_uri'), table_name='functions')
    op.drop_column('functions', 'uri')
    # ### end Alembic commands ###
