"""add group

Revision ID: 249d9c06f79f
Revises: a0d862cc3361
Create Date: 2025-08-01 16:22:18.105098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '249d9c06f79f'
down_revision: Union[str, None] = 'a0d862cc3361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('group', sa.String(length=50), nullable=True))
    op.add_column('functions', sa.Column('group', sa.String(length=50), nullable=True))
    op.add_column('menus', sa.Column('group', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'group')
    op.drop_column('functions', 'group')
    op.drop_column('components', 'group')
    # ### end Alembic commands ###
