"""add job

Revision ID: 2fad772e620f
Revises: e9bcaa1f9443
Create Date: 2025-08-15 17:48:38.816652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fad772e620f'
down_revision: Union[str, None] = 'e9bcaa1f9443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_id', sa.Integer(), nullable=True, comment='岗位ID'))
    op.create_foreign_key(None, 'users', 'jobs', ['job_id'], ['job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'job_id')
    # ### end Alembic commands ###
