"""models changed

Revision ID: 35d1bff6a191
Revises: dbee45498853
Create Date: 2025-08-04 20:50:03.897069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '35d1bff6a191'
down_revision: Union[str, None] = 'dbee45498853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('utime', sa.DateTime(), nullable=True, comment='更新时间'))
    op.alter_column('components', 'component_name',
               existing_type=mysql.VARCHAR(length=50),
               comment='组件名称',
               existing_nullable=True)
    op.alter_column('components', 'status',
               existing_type=mysql.VARCHAR(length=5),
               comment='状态：0-正常，1-禁用',
               existing_nullable=True)
    op.alter_column('components', 'ctime',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('components', 'group',
               existing_type=mysql.VARCHAR(length=50),
               comment='分组名称',
               existing_nullable=True)
    op.alter_column('components', 'group_id',
               existing_type=mysql.INTEGER(),
               comment='分组ID',
               existing_nullable=True)
    op.alter_column('functions', 'func_name',
               existing_type=mysql.VARCHAR(length=50),
               comment='功能名称',
               existing_nullable=True)
    op.alter_column('functions', 'status',
               existing_type=mysql.VARCHAR(length=5),
               comment='状态：0-正常，1-禁用',
               existing_nullable=True)
    op.alter_column('functions', 'ctime',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('functions', 'utime',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)
    op.alter_column('functions', 'method_type',
               existing_type=mysql.VARCHAR(length=10),
               comment='请求方法',
               existing_nullable=True)
    op.alter_column('functions', 'group',
               existing_type=mysql.VARCHAR(length=50),
               comment='分组名称',
               existing_nullable=True)
    op.alter_column('functions', 'group_id',
               existing_type=mysql.INTEGER(),
               comment='分组ID',
               existing_nullable=True)
    op.drop_column('functions', 'uri')
    op.alter_column('groups', 'group_name',
               existing_type=mysql.VARCHAR(length=50),
               comment='分组名称',
               existing_nullable=True)
    op.alter_column('groups', 'description',
               existing_type=mysql.VARCHAR(length=200),
               comment='分组描述',
               existing_nullable=True)
    op.alter_column('groups', 'status',
               existing_type=mysql.VARCHAR(length=5),
               comment='状态：0-正常，1-禁用',
               existing_nullable=True)
    op.alter_column('groups', 'ctime',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('groups', 'utime',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)
    op.drop_index(op.f('ix_groups_group_code'), table_name='groups')
    op.drop_column('groups', 'group_code')
    op.alter_column('menus', 'menu_name',
               existing_type=mysql.VARCHAR(length=50),
               comment='菜单名称',
               existing_nullable=True)
    op.alter_column('menus', 'status',
               existing_type=mysql.VARCHAR(length=5),
               comment='状态：0-正常，1-禁用',
               existing_nullable=True)
    op.alter_column('menus', 'ctime',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('menus', 'utime',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)
    op.alter_column('menus', 'group',
               existing_type=mysql.VARCHAR(length=50),
               comment='分组名称',
               existing_nullable=True)
    op.alter_column('menus', 'group_id',
               existing_type=mysql.INTEGER(),
               comment='分组ID',
               existing_nullable=True)
    op.alter_column('menus', 'parent_id',
               existing_type=mysql.INTEGER(),
               comment='父菜单ID',
               existing_nullable=True)
    op.alter_column('menus', 'order_num',
               existing_type=mysql.INTEGER(),
               comment='排序字段',
               existing_nullable=True)
    op.alter_column('menus', 'icon',
               existing_type=mysql.VARCHAR(length=50),
               comment='菜单图标',
               existing_nullable=True)
    op.add_column('role_components', sa.Column('utime', sa.DateTime(), nullable=True, comment='更新时间'))
    op.alter_column('role_components', 'ctime',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.add_column('role_functions', sa.Column('utime', sa.DateTime(), nullable=True, comment='更新时间'))
    op.alter_column('role_functions', 'ctime',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.add_column('role_menus', sa.Column('utime', sa.DateTime(), nullable=True, comment='更新时间'))
    op.alter_column('role_menus', 'ctime',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.add_column('roles', sa.Column('role_desc', sa.Text(), nullable=True, comment='角色描述'))
    op.add_column('roles', sa.Column('utime', sa.DateTime(), nullable=True, comment='更新时间'))
    op.alter_column('roles', 'role_name',
               existing_type=mysql.VARCHAR(length=50),
               comment='角色名称',
               existing_nullable=True)
    op.alter_column('roles', 'status',
               existing_type=mysql.VARCHAR(length=5),
               comment='状态：0-正常，1-禁用',
               existing_nullable=True)
    op.alter_column('roles', 'ctime',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('roles', 'projects',
               existing_type=mysql.VARCHAR(length=255),
               comment='项目列表',
               existing_nullable=True)
    op.alter_column('roles', 'group',
               existing_type=mysql.VARCHAR(length=50),
               comment='分组名称',
               existing_nullable=True)
    op.alter_column('roles', 'group_id',
               existing_type=mysql.INTEGER(),
               comment='分组ID',
               existing_nullable=True)
    op.add_column('user_roles', sa.Column('utime', sa.DateTime(), nullable=True, comment='更新时间'))
    op.alter_column('user_roles', 'ctime',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.add_column('users', sa.Column('utime', sa.DateTime(), nullable=True, comment='更新时间'))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment='英文名称',
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=100),
               comment='用户密码',
               existing_nullable=True)
    op.alter_column('users', 'nickname',
               existing_type=mysql.VARCHAR(length=100),
               comment='中文名称',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=80),
               comment='邮箱地址',
               existing_nullable=True)
    op.alter_column('users', 'tel',
               existing_type=mysql.VARCHAR(length=11),
               comment='电话号码',
               existing_nullable=True)
    op.alter_column('users', 'wechat',
               existing_type=mysql.VARCHAR(length=50),
               comment='微信名称',
               existing_nullable=True)
    op.alter_column('users', 'department',
               existing_type=mysql.VARCHAR(length=50),
               comment='组织名称',
               existing_nullable=True)
    op.alter_column('users', 'superuser',
               existing_type=mysql.VARCHAR(length=5),
               comment='管理员',
               existing_nullable=True)
    op.alter_column('users', 'status',
               existing_type=mysql.VARCHAR(length=5),
               comment='状态：0-正常，1-禁用',
               existing_nullable=True)
    op.alter_column('users', 'last_ip',
               existing_type=mysql.VARCHAR(length=20),
               comment='最后登录IP',
               existing_nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=mysql.DATETIME(),
               comment='最后登录时间',
               existing_nullable=True)
    op.alter_column('users', 'disable_at',
               existing_type=mysql.DATETIME(),
               comment='禁用时间',
               existing_nullable=True)
    op.alter_column('users', 'wechat_userid',
               existing_type=mysql.VARCHAR(length=50),
               comment='微信ID',
               existing_nullable=True)
    op.alter_column('users', 'dingtalk_userid',
               existing_type=mysql.VARCHAR(length=50),
               comment='钉钉ID',
               existing_nullable=True)
    op.alter_column('users', 'feishu_userid',
               existing_type=mysql.VARCHAR(length=50),
               comment='飞书ID',
               existing_nullable=True)
    op.alter_column('users', 'avatar',
               existing_type=mysql.VARCHAR(length=256),
               comment='头像地址',
               existing_nullable=True)
    op.alter_column('users', 'ctime',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.drop_column('users', 'google_key')
    op.drop_column('users', 'no')
    op.drop_column('users', 'dept')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dept', mysql.JSON(), nullable=True))
    op.add_column('users', sa.Column('no', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('google_key', mysql.VARCHAR(length=80), nullable=True))
    op.alter_column('users', 'ctime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('users', 'avatar',
               existing_type=mysql.VARCHAR(length=256),
               comment=None,
               existing_comment='头像地址',
               existing_nullable=True)
    op.alter_column('users', 'feishu_userid',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='飞书ID',
               existing_nullable=True)
    op.alter_column('users', 'dingtalk_userid',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='钉钉ID',
               existing_nullable=True)
    op.alter_column('users', 'wechat_userid',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='微信ID',
               existing_nullable=True)
    op.alter_column('users', 'disable_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='禁用时间',
               existing_nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='最后登录时间',
               existing_nullable=True)
    op.alter_column('users', 'last_ip',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='最后登录IP',
               existing_nullable=True)
    op.alter_column('users', 'status',
               existing_type=mysql.VARCHAR(length=5),
               comment=None,
               existing_comment='状态：0-正常，1-禁用',
               existing_nullable=True)
    op.alter_column('users', 'superuser',
               existing_type=mysql.VARCHAR(length=5),
               comment=None,
               existing_comment='管理员',
               existing_nullable=True)
    op.alter_column('users', 'department',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='组织名称',
               existing_nullable=True)
    op.alter_column('users', 'wechat',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='微信名称',
               existing_nullable=True)
    op.alter_column('users', 'tel',
               existing_type=mysql.VARCHAR(length=11),
               comment=None,
               existing_comment='电话号码',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=80),
               comment=None,
               existing_comment='邮箱地址',
               existing_nullable=True)
    op.alter_column('users', 'nickname',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='中文名称',
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='用户密码',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='英文名称',
               existing_nullable=True)
    op.drop_column('users', 'utime')
    op.alter_column('user_roles', 'ctime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('user_roles', 'utime')
    op.alter_column('roles', 'group_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='分组ID',
               existing_nullable=True)
    op.alter_column('roles', 'group',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='分组名称',
               existing_nullable=True)
    op.alter_column('roles', 'projects',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='项目列表',
               existing_nullable=True)
    op.alter_column('roles', 'ctime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('roles', 'status',
               existing_type=mysql.VARCHAR(length=5),
               comment=None,
               existing_comment='状态：0-正常，1-禁用',
               existing_nullable=True)
    op.alter_column('roles', 'role_name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='角色名称',
               existing_nullable=True)
    op.drop_column('roles', 'utime')
    op.drop_column('roles', 'role_desc')
    op.alter_column('role_menus', 'ctime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('role_menus', 'utime')
    op.alter_column('role_functions', 'ctime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('role_functions', 'utime')
    op.alter_column('role_components', 'ctime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.drop_column('role_components', 'utime')
    op.alter_column('menus', 'icon',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='菜单图标',
               existing_nullable=True)
    op.alter_column('menus', 'order_num',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='排序字段',
               existing_nullable=True)
    op.alter_column('menus', 'parent_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='父菜单ID',
               existing_nullable=True)
    op.alter_column('menus', 'group_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='分组ID',
               existing_nullable=True)
    op.alter_column('menus', 'group',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='分组名称',
               existing_nullable=True)
    op.alter_column('menus', 'utime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('menus', 'ctime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('menus', 'status',
               existing_type=mysql.VARCHAR(length=5),
               comment=None,
               existing_comment='状态：0-正常，1-禁用',
               existing_nullable=True)
    op.alter_column('menus', 'menu_name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='菜单名称',
               existing_nullable=True)
    op.add_column('groups', sa.Column('group_code', mysql.VARCHAR(length=50), nullable=True))
    op.create_index(op.f('ix_groups_group_code'), 'groups', ['group_code'], unique=True)
    op.alter_column('groups', 'utime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('groups', 'ctime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('groups', 'status',
               existing_type=mysql.VARCHAR(length=5),
               comment=None,
               existing_comment='状态：0-正常，1-禁用',
               existing_nullable=True)
    op.alter_column('groups', 'description',
               existing_type=mysql.VARCHAR(length=200),
               comment=None,
               existing_comment='分组描述',
               existing_nullable=True)
    op.alter_column('groups', 'group_name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='分组名称',
               existing_nullable=True)
    op.add_column('functions', sa.Column('uri', mysql.VARCHAR(length=256), nullable=True))
    op.alter_column('functions', 'group_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='分组ID',
               existing_nullable=True)
    op.alter_column('functions', 'group',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='分组名称',
               existing_nullable=True)
    op.alter_column('functions', 'method_type',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='请求方法',
               existing_nullable=True)
    op.alter_column('functions', 'utime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('functions', 'ctime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('functions', 'status',
               existing_type=mysql.VARCHAR(length=5),
               comment=None,
               existing_comment='状态：0-正常，1-禁用',
               existing_nullable=True)
    op.alter_column('functions', 'func_name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='功能名称',
               existing_nullable=True)
    op.alter_column('components', 'group_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='分组ID',
               existing_nullable=True)
    op.alter_column('components', 'group',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='分组名称',
               existing_nullable=True)
    op.alter_column('components', 'ctime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('components', 'status',
               existing_type=mysql.VARCHAR(length=5),
               comment=None,
               existing_comment='状态：0-正常，1-禁用',
               existing_nullable=True)
    op.alter_column('components', 'component_name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='组件名称',
               existing_nullable=True)
    op.drop_column('components', 'utime')
    # ### end Alembic commands ###
