"""function model change

Revision ID: 49fc84cf0e3e
Revises: 9a60cf223e67
Create Date: 2025-08-01 18:33:23.232240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '49fc84cf0e3e'
down_revision: Union[str, None] = '9a60cf223e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('utime', sa.DateTime(), nullable=True))
    op.add_column('functions', sa.Column('uri', sa.String(length=256), nullable=True))
    op.add_column('functions', sa.Column('method_type', sa.String(length=10), nullable=True))
    op.drop_index(op.f('ix_functions_func_code'), table_name='functions')
    op.drop_column('functions', 'func_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('func_code', mysql.VARCHAR(length=50), nullable=True))
    op.create_index(op.f('ix_functions_func_code'), 'functions', ['func_code'], unique=True)
    op.drop_column('functions', 'method_type')
    op.drop_column('functions', 'uri')
    op.drop_column('functions', 'utime')
    # ### end Alembic commands ###
