"""用户表增加工号、性别两个字段

Revision ID: 847f3a7ded1b
Revises: 1e0cc7e9c46e
Create Date: 2025-10-29 11:41:38.738100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '847f3a7ded1b'
down_revision: Union[str, None] = '1e0cc7e9c46e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sa.String(length=50), nullable=True, comment='工号'))
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True, comment='性别'))
    op.alter_column('users', 'department',
               existing_type=mysql.VARCHAR(length=50),
               comment='主部门',
               existing_comment='组织名称',
               existing_nullable=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.alter_column('users', 'department',
               existing_type=mysql.VARCHAR(length=50),
               comment='组织名称',
               existing_comment='主部门',
               existing_nullable=True)
    op.drop_column('users', 'gender')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###
