"""调整用户和岗位的关系

Revision ID: 85a1894334e8
Revises: 847f3a7ded1b
Create Date: 2025-10-30 13:55:52.529418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '85a1894334e8'
down_revision: Union[str, None] = '847f3a7ded1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_ibfk_1'), 'users', type_='foreignkey')
    op.drop_column('users', 'job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='岗位ID'))
    op.create_foreign_key(op.f('users_ibfk_1'), 'users', 'jobs', ['job_id'], ['job_id'])
    # ### end Alembic commands ###
