"""init

Revision ID: a0d862cc3361
Revises: 
Create Date: 2025-07-03 11:56:25.068581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d862cc3361'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('group_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.Column('utime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_groups_group_code'), 'groups', ['group_code'], unique=True)
    op.create_index(op.f('ix_groups_group_id'), 'groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_groups_group_name'), 'groups', ['group_name'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('tel', sa.String(length=11), nullable=True),
    sa.Column('wechat', sa.String(length=50), nullable=True),
    sa.Column('no', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('google_key', sa.String(length=80), nullable=True),
    sa.Column('superuser', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=True),
    sa.Column('last_ip', sa.String(length=20), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('disable_at', sa.DateTime(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.Column('wechat_userid', sa.String(length=50), nullable=True),
    sa.Column('dingtalk_userid', sa.String(length=50), nullable=True),
    sa.Column('feishu_userid', sa.String(length=50), nullable=True),
    sa.Column('dept', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('components',
    sa.Column('component_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('component_name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.create_index(op.f('ix_components_component_id'), 'components', ['component_id'], unique=False)
    op.create_index(op.f('ix_components_component_name'), 'components', ['component_name'], unique=True)
    op.create_table('functions',
    sa.Column('func_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('func_name', sa.String(length=50), nullable=True),
    sa.Column('func_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('func_id')
    )
    op.create_index(op.f('ix_functions_func_code'), 'functions', ['func_code'], unique=True)
    op.create_index(op.f('ix_functions_func_id'), 'functions', ['func_id'], unique=False)
    op.create_index(op.f('ix_functions_func_name'), 'functions', ['func_name'], unique=True)
    op.create_table('menus',
    sa.Column('menu_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('menu_id')
    )
    op.create_index(op.f('ix_menus_menu_id'), 'menus', ['menu_id'], unique=False)
    op.create_index(op.f('ix_menus_menu_name'), 'menus', ['menu_name'], unique=True)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.Column('projects', sa.String(length=255), nullable=True),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    op.create_table('role_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_components_id'), 'role_components', ['id'], unique=False)
    op.create_table('role_functions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('func_id', sa.Integer(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['func_id'], ['functions.func_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_functions_id'), 'role_functions', ['id'], unique=False)
    op.create_table('role_menus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.menu_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_menus_id'), 'role_menus', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_role_menus_id'), table_name='role_menus')
    op.drop_table('role_menus')
    op.drop_index(op.f('ix_role_functions_id'), table_name='role_functions')
    op.drop_table('role_functions')
    op.drop_index(op.f('ix_role_components_id'), table_name='role_components')
    op.drop_table('role_components')
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_menus_menu_name'), table_name='menus')
    op.drop_index(op.f('ix_menus_menu_id'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_functions_func_name'), table_name='functions')
    op.drop_index(op.f('ix_functions_func_id'), table_name='functions')
    op.drop_index(op.f('ix_functions_func_code'), table_name='functions')
    op.drop_table('functions')
    op.drop_index(op.f('ix_components_component_name'), table_name='components')
    op.drop_index(op.f('ix_components_component_id'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_groups_group_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_group_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_group_code'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
