"""菜单移除group关联关系

Revision ID: a601bfea69c7
Revises: 2fad772e620f
Create Date: 2025-10-15 17:57:09.732100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a601bfea69c7'
down_revision: Union[str, None] = '2fad772e620f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'job_code',
               existing_type=mysql.VARCHAR(length=50),
               comment='岗位编码',
               existing_comment='工种编码',
               existing_nullable=True)
    op.alter_column('jobs', 'job_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='岗位名称',
               existing_comment='工种名称',
               existing_nullable=True)
    op.alter_column('jobs', 'description',
               existing_type=mysql.VARCHAR(length=255),
               comment='岗位描述',
               existing_comment='工种描述',
               existing_nullable=True)
    op.drop_constraint(op.f('menus_ibfk_1'), 'menus', type_='foreignkey')
    op.drop_column('menus', 'group_id')
    op.drop_column('menus', 'group')
    op.alter_column('organizations', 'org_type',
               existing_type=mysql.INTEGER(),
               comment='组织类型：1-组织，2-部门，3-团队，4-团队',
               existing_comment='组织类型：1-组织，2-部门，3-团队',
               existing_nullable=True)
    op.drop_constraint(op.f('positions_ibfk_1'), 'positions', type_='foreignkey')
    op.drop_column('positions', 'org_id')
    op.alter_column('users', 'job_id',
               existing_type=mysql.INTEGER(),
               comment='岗位ID',
               existing_comment='工种ID',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'job_id',
               existing_type=mysql.INTEGER(),
               comment='工种ID',
               existing_comment='岗位ID',
               existing_nullable=True)
    op.add_column('positions', sa.Column('org_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='所属组织ID'))
    op.create_foreign_key(op.f('positions_ibfk_1'), 'positions', 'organizations', ['org_id'], ['org_id'])
    op.alter_column('organizations', 'org_type',
               existing_type=mysql.INTEGER(),
               comment='组织类型：1-组织，2-部门，3-团队',
               existing_comment='组织类型：1-组织，2-部门，3-团队，4-团队',
               existing_nullable=True)
    op.add_column('menus', sa.Column('group', mysql.VARCHAR(length=50), nullable=True, comment='分组名称'))
    op.add_column('menus', sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='分组ID'))
    op.create_foreign_key(op.f('menus_ibfk_1'), 'menus', 'groups', ['group_id'], ['group_id'])
    op.alter_column('jobs', 'description',
               existing_type=mysql.VARCHAR(length=255),
               comment='工种描述',
               existing_comment='岗位描述',
               existing_nullable=True)
    op.alter_column('jobs', 'job_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='工种名称',
               existing_comment='岗位名称',
               existing_nullable=True)
    op.alter_column('jobs', 'job_code',
               existing_type=mysql.VARCHAR(length=50),
               comment='工种编码',
               existing_comment='岗位编码',
               existing_nullable=True)
    # ### end Alembic commands ###
