"""add org/position

Revision ID: e9bcaa1f9443
Revises: 230963af0176
Create Date: 2025-08-15 14:48:53.150399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9bcaa1f9443'
down_revision: Union[str, None] = '230963af0176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('org_type', sa.Integer(), nullable=True, comment='组织类型：1-组织，2-部门，3-团队'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'org_type')
    # ### end Alembic commands ###
