"""add menu tree

Revision ID: f55f080df2a5
Revises: 49fc84cf0e3e
Create Date: 2025-08-04 16:46:29.079527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55f080df2a5'
down_revision: Union[str, None] = '49fc84cf0e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('utime', sa.DateTime(), nullable=True))
    op.add_column('menus', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('menus', sa.Column('order_num', sa.Integer(), nullable=True))
    op.add_column('menus', sa.Column('icon', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'menus', 'menus', ['parent_id'], ['menu_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.drop_column('menus', 'icon')
    op.drop_column('menus', 'order_num')
    op.drop_column('menus', 'parent_id')
    op.drop_column('menus', 'utime')
    # ### end Alembic commands ###
